### ISSUE TITLE
Lugar de la entrega 1

### ISSUE THREAD

**Issue by domingo2000** [IIC2513-2021-2/project#2]
Hola, tengo una duda, la entrega 1 también va en una carpeta que diga E1??,  O ya debemos montar el proyecto en la carpeta raiz del repo. Si es que se debe montar en el root, como corro yeoman para generar el template del curso en al carpeta root y no en un sub directorio?? O es simplemente hacer copy paste en el root luego de crear el template?

**Comment by dasolari** [comment]
Hola! 
De ahora en adelante no es necesario dejar las entregas en carpetas "EX" (X siendo el número de la entrega). Puedes crear tu app en la raíz de tu repo y quedará en un directorio junto con la E0, pero si deseas puedes sacar todos los archivos del directorio que tenga tu app y moverlos a la raíz. Si decides hacer esto último, ten cuidado con los archivos ocultos del proyecto, debes moverlos todos.

**Comment by domingo2000** [comment]
perfecto, y luego para hacer el deploy a heroku no importa entonces que el proyecto no este en el root del repo?

**Comment by dasolari** [comment]
Si importa, en caso de que lo dejes en un sub directorio debes usar este [buildpack](https://github.com/timanovsky/subdir-heroku-buildpack).

**Comment by Baelfire18** [comment]
Hola @domingo2000, es bastante recomendable hacerlo en el directorio raíz del repositorio. 

Para hacerlo directamente solo deberás correr el proyecto con un punto en lugar del nombre del proyecto
```bash
yo @iic2513/template .
```
Eso si me parece que esto hará que tu nombre del proyecto sea `.` y es posible que quede en algún archivo como `package.json` (lo puedes cambiar a mano).

Por demás de Heroku recomendaría dejarlo en tu repo raíz.

**Comment by domingo2000** [comment]
@Baelfire18 intenté corriendo ese comando anteriormente pero me arroja error yarn y dice que el proyecto no puede tener como nombre "."

**Comment by Baelfire18** [comment]
Ok, entonces puedes crearlo en un subdirectorio como:
```bash
yo @iic2513/template my_app
```
y luego mover todos los archivos del subdirectorio al directorio raiz con este comando:
```bash
mv my_app/* ./
```

**Comment by domingo2000** [comment]
![image](https://user-images.githubusercontent.com/40220174/134595870-59f01bde-2dcd-4385-a35e-343eb77e1f17.png)
Hola, acabo de hacer eso y hay algunos archivos que aún así no se movieron, algun consejo?

**Comment by Baelfire18** [comment]
Al parecer te quedaron los dotfiles, prueba con 
```bash
mv my_app/* my_app/.* ./
```
parado desde el repo raíz

**Comment by domingo2000** [comment]
Al final movi todo usando el explorer de windows! Gracias!

**Comment by sivicencio** [comment]
Para quienes tengan un problema similar, en caso de que hayan creado el proyecto con el template dentro de un subdirectorio de la raíz del repositorio, la solución recomendada es correr el siguiente comando dentro del directorio creado con el template:
```bash
mv $(ls -A) ..
```

**Comment by FdoTorres1** [comment]
> Para quienes tengan un problema similar, en caso de que hayan creado el proyecto con el template dentro de un subdirectorio de la raíz del repositorio, la solución recomendada es correr el siguiente comando dentro del directorio creado con el template:
> 
> ```shell
> mv $(ls -A) ..
> ```

Hola, seguí esto pero me equivoqué y lo corrí en el directorio raíz del repo en vez de hacerlo en el subdirectorio, cómo lo puedo revertir? Gracias.
