### ISSUE TITLE
Problema con la base de datos

### ISSUE THREAD

**Issue by oerlandsen** [IIC2513-2021-2/project#20]
Hola! 
Mi problema es que en la consola de postgres creo una nueva base de datos y después me dice que no existe. Cuando hago \list me aparece y al hacer el db:migrate sale  ERROR: no existe la base de datos �iic2513template_dev�.    iic2513template_dev es el nombre de la db.

**Comment by meretamal** [comment]
Hola 😁, puedes ingresar a psql, correr `\conninfo` y mandar tu _output_?

**Comment by oerlandsen** [comment]
You are connected to database "postgres" as user "postgres" via socket in "/var/run/postgresql" at port "5433".

**Comment by Baelfire18** [comment]
@oerlandsen Creaste un `.env` con esto (rellenado claro)?:
```bash
DB_USERNAME=
DB_PASSWORD=
DB_NAME=
```
Y al principio de  un archivo `src\config\database.js` importas esto? `require('dotenv').config();`

**Comment by oerlandsen** [comment]
si

**Comment by meretamal** [comment]
@oerlandsen lo que pasa es que tu servicio está corriendo en el puerto 5433 y por default postgres corre en el 5432 (probablemente tenías este puerto ocupado). El template está configurado para usar el 5432. Tienes dos opciones:
1. Agregar a tus variables de entorno una variable llamada `DB_PORT` que sea igual a 5433, luego en **database.js**, en `default` agrega la propiedad `port: process.env.DB_PORT || 5432`.
2. Termina el servicio que esté corriendo en el puerto 5432, cambia la configuración de postgres con tal de que empiece a usar el puerto correcto y reinicia tu servicio de postgres

**Comment by oerlandsen** [comment]
Funcionó!! gracias!!!!
