### ISSUE TITLE
Lazy loading association

### ISSUE THREAD

**Issue by PedroFuenzalida** [IIC2513-2021-2/project#26]
Hola! Estamos intentando usar una función .getUser() como se hizo en la cápsula, pero tira error diciendo que no existe la función.

**Comment by meretamal** [comment]
Hola 😁, si es que el usuario tiene una relación 1:n con otro recurso (siendo el otro recurso la "n"), es necesario que este último tenga la asociación _belongsTo_ a _user_ para poder usar el método `getUser`

**Comment by PedroFuenzalida** [comment]
Ahi lo logré solucionar! Le estaba pasando un parámetro malo al belongsTo... gracias!
