### ISSUE TITLE
Problema slint post fix y arreglos 

### ISSUE THREAD

**Issue by Gianluc139** [IIC2513-2021-2/project#37]
![image](https://user-images.githubusercontent.com/53875541/137034640-9a201199-beb8-432d-91e7-be54c02b1920.png)

Hola, despues de corregir todo lo que pedia el slint como sale en la capsula, aun asi al intentar hacer un merge nos aparece este error. Es muy extraño porque dice que no encuentra el package.json en s2-grupo-los-promesa/s2-grupo-los-promesa, y eso esta bien ya que no tenemos que tener la carpeta del repositorio dentro de si misma con el mismo nombre. La ubicacion de nuestra app es  s2-grupo-los-promesa/E1/UrbanGarden.

**Comment by meretamal** [comment]
Hola :grin:, la action está configurada para correr `eslint` en la raíz del repo, por lo que tu proyecto debería estar ahí y no en un subdirectorio.

Si te paras en la carpeta de tu proyecto y correr `mv $(ls -A) ..` se debería mover todo una carpeta atrás.

**Comment by sivicencio** [comment]
Hola. La ubicación que aparece como `s2-grupo-los-promesa/s2-grupo-los-promesa` puedes ignorarla, pues tiene que ver con el funcionamiento interno de la Github Action.

Tal como dice @meretamal, el error ocurre porque no tienen el proyecto koa en la raíz del repositorio. La Github Action supone que esa es la ubicación y, por lo tanto, al intentar buscar ahí el archivo `package.json`, no lo encuentra.
